### ISSUE TITLE
You need to specify your imap password and save it with the --savepw switch

### ISSUE THREAD

**Issue by praul** [DumpName/docker_isbg#15]
Hi there and thanks, this is just what I was looking for. I don't know if it's running correctly. It does not seem to detect spam. In logs I always get 'You need to specify your imap password and save it with the --savepw switch'. Is this normal behaviour and everything is working fine? Thank you

```Handling config file 2
isbg-isbg-1  | 0 spams moved to learn
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost XXX.com --spamc --imapuser YYY@XXX.com  --partialrun 50 --maxsize 120000  --delete --expunge --spaminbox Spam --passwdfilename /var/lib/mailaccounts/XXX_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track649f83c094f18dd93ac3c4aa30da9bdb
isbg-isbg-1  | Password file is /var/lib/mailaccounts/XXX.conf
isbg-isbg-1  | SpamFlags are ['\\Deleted']
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments```

**Comment by DumpName** [comment]
I will have a look into this. However your issue is missing a lot of usefull information for debugging purposes:
- Please provide a full log output (ideally with the environment `DETAILED_LOGGING` set to `true` as the startup process is cut from your log output.
- What does your Mail config look like? Have you set a password inside the config file as required?
From my perspective this looks like you either did provide an empty password in the config file or no password at all.

**Comment by praul** [comment]
Yes I have set a password in mail configs and am not getting any other log-in related issues. It also lists imap folders correctly on startup, so it must use the password somehow. I will add a complete log.

 

I suspect this is somehow a false verbose output since passwords are handled… differently?

 

Von: Christian H. ***@***.***> 
Gesendet: Samstag, 7. Dezember 2024 14:49
An: DumpName/docker_isbg ***@***.***>
Cc: praul ***@***.***>; Author ***@***.***>
Betreff: Re: [DumpName/docker_isbg] You need to specify your imap password and save it with the --savepw switch (Issue #15)

 

I will have a look into this. However your issue is missing a lot of usefull information for debugging purposes:

*	Please provide a full log output (ideally with the environment DETAILED_LOGGING set to true as the startup process is cut from your log output.
*	What does your Mail config look like? Have you set a password inside the config file as required?
From my perspective this looks like you either did provide an empty password in the config file or no password at all.

**Comment by DumpName** [comment]
The output you are getting is comming direct from isbg ([code](https://gitlab.com/isbg/isbg/-/blob/master/isbg/isbg.py#L453)). As the isbg is reaching this line of code it should already have read the password / config file.

**Comment by praul** [comment]
Full log:

```docker compose up -d && docker compose logs -f
[+] Running 2/2
 ⠿ Network isbg_default   Created                                                                                                                                                          0.3s
 ⠿ Container isbg-isbg-1  Started                                                                                                                                                          1.5s
isbg-isbg-1  | su: invalid option -- 'r'
isbg-isbg-1  | Try 'su --help' for more information.
isbg-isbg-1  | Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 442.
isbg-isbg-1  | Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 443.
isbg-isbg-1  | Found 2 Config Files!
isbg-isbg-1  | Handling config file 1
isbg-isbg-1  | Mailbox mail1@redacted.com@smtp.redacted.com contains:
isbg-isbg-1  | ######MAILBOXES######

... [REDACTED] List of folders

isbg-isbg-1  | #######FOLDERS#######
isbg-isbg-1  | INBOX
isbg-isbg-1  | Handling config file 2
isbg-isbg-1  | Mailbox mail2@redacted.com@redacted.com contains:
isbg-isbg-1  | ######MAILBOXES######

... [REDACTED] List of folders

isbg-isbg-1  | #######FOLDERS#######

... [REDACTED] List of folders

isbg-isbg-1  | running sa-learn
isbg-isbg-1  | starting spamassassin
isbg-isbg-1  | Starting SpamAssassin Mail Filter Daemon: spamd.
isbg-isbg-1  | updating SpamAssassin rules
isbg-isbg-1  | Update finished, no fresh updates were available
isbg-isbg-1  | SpamTrainer Found 2 Config Files!
isbg-isbg-1  | Handling config file 1
isbg-isbg-1  | Training Spam for /var/lib/mailaccounts/mail1_redacted_com.conf
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost smtp.redacted.com --imapuser mail1@redacted.com --spamc --teachonly --maxsize 120000 --partialrun 50 --learnspambox Spam --passwdfilename /var/lib/mailaccounts/mail1_redacted_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/tracka31675bda47195b924a0947a880c2983
isbg-isbg-1  | Password file is /var/lib/mailaccounts/mail1_redacted_com.conf
isbg-isbg-1  | SpamFlags are []
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost smtp.redacted.com --imapuser mail1@redacted.com --spamc --teachonly --maxsize 120000 --partialrun 50 --learnhambox KeinSpam --passwdfilename /var/lib/mailaccounts/mail1_redacted_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/tracka31675bda47195b924a0947a880c2983
isbg-isbg-1  | Password file is /var/lib/mailaccounts/mail1_redacted_com.conf
isbg-isbg-1  | SpamFlags are []
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments
isbg-isbg-1  | 0 hams moved
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost smtp.redacted.com --imapuser mail1@redacted.com --spamc --teachonly --maxsize 120000 --partialrun 50 --learnhambox Sent --passwdfilename /var/lib/mailaccounts/mail1_redacted_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/tracka31675bda47195b924a0947a880c2983
isbg-isbg-1  | Password file is /var/lib/mailaccounts/mail1_redacted_com.conf
isbg-isbg-1  | SpamFlags are []
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments
isbg-isbg-1  | 0 spams deleted
isbg-isbg-1  | Handling config file 2
isbg-isbg-1  | Training Spam for /var/lib/mailaccounts/mail2_redacted_com.conf
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted.com --imapuser mail2@redacted.com --spamc --teachonly --maxsize 120000 --partialrun 50 --learnspambox Spam --passwdfilename /var/lib/mailaccounts/mail2_redacted_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track649f83c094f18dd93ac3c4aa30da9bdb
isbg-isbg-1  | Password file is /var/lib/mailaccounts/mail2_redacted_com.conf
isbg-isbg-1  | SpamFlags are []
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted.com --imapuser mail2@redacted.com --spamc --teachonly --maxsize 120000 --partialrun 50 --learnhambox KeinSpam --passwdfilename /var/lib/mailaccounts/mail2_redacted_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track649f83c094f18dd93ac3c4aa30da9bdb
isbg-isbg-1  | Password file is /var/lib/mailaccounts/mail2_redacted_com.conf
isbg-isbg-1  | SpamFlags are []
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments
isbg-isbg-1  | 0 hams moved
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted.com --imapuser mail2@redacted.com --spamc --teachonly --maxsize 120000 --partialrun 50 --learnhambox Sent --passwdfilename /var/lib/mailaccounts/mail2_redacted_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track649f83c094f18dd93ac3c4aa30da9bdb
isbg-isbg-1  | Password file is /var/lib/mailaccounts/mail2_redacted_com.conf
isbg-isbg-1  | SpamFlags are []
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments
isbg-isbg-1  | 0 spams deleted
isbg-isbg-1  | starting Main Loop
isbg-isbg-1  | Spam Filter found 2 Config Files!
isbg-isbg-1  | Handling config file 1
isbg-isbg-1  | 0 spams moved to learn
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost smtp.redacted.com --spamc --imapuser mail1@redacted.com  --partialrun 50 --maxsize 120000  --delete --expunge --spaminbox Spam --passwdfilename /var/lib/mailaccounts/mail1_redacted_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/tracka31675bda47195b924a0947a880c2983
isbg-isbg-1  | Password file is /var/lib/mailaccounts/mail1_redacted_com.conf
isbg-isbg-1  | SpamFlags are ['\\Deleted']
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments
isbg-isbg-1  | Handling config file 2
isbg-isbg-1  | 0 spams moved to learn
isbg-isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted.com --spamc --imapuser mail2@redacted.com  --partialrun 50 --maxsize 120000  --delete --expunge --spaminbox Spam --passwdfilename /var/lib/mailaccounts/mail2_redacted_com.conf --verbose " $USERNAME
isbg-isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg-isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track649f83c094f18dd93ac3c4aa30da9bdb
isbg-isbg-1  | Password file is /var/lib/mailaccounts/mail2_redacted_com.conf
isbg-isbg-1  | SpamFlags are ['\\Deleted']
isbg-isbg-1  | You need to specify your imap password and save it with the --savepw switch
isbg-isbg-1  | Use --help to see valid options and arguments```

**Comment by praul** [comment]
> The output you are getting is comming direct from isbg ([code](https://gitlab.com/isbg/isbg/-/blob/master/isbg/isbg.py#L453)). As the isbg is reaching this line of code it should already have read the password / config file.

Okay thanks, so ignore and everything does work as it should. Will monitor if it detects and handles any spam. Thank you

**Comment by DumpName** [comment]
When isbg cannot login ypour docker container would only handle spam that has already been flagged by your email provider.
Without looking into your config file I am not able to identify why the password works for imapfilter bur not for isbg.
However I fully undestand that sharing the config file is not possible.
Sadly 
I was not able to reproduce this issue.

**Comment by praul** [comment]
I created a fresh test-mail acccount and docker compose folder but the logs looks the same:
Do you have an email-adress or similar, then I could share the config file?

``# docker compose up
isbg_testing-isbg_testing-1  | su: invalid option -- 'r'
isbg_testing-isbg_testing-1  | Try 'su --help' for more information.
isbg_testing-isbg_testing-1  | Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 442.
isbg_testing-isbg_testing-1  | Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 443.
isbg_testing-isbg_testing-1  | Found 1 Config Files!
isbg_testing-isbg_testing-1  | Handling config file 1
isbg_testing-isbg_testing-1  | Mailbox isbg_test@heimpixel.de@imap.ionos.de contains:
isbg_testing-isbg_testing-1  | ######MAILBOXES######
isbg_testing-isbg_testing-1  | Entwürfe
isbg_testing-isbg_testing-1  | Gesendete Objekte
isbg_testing-isbg_testing-1  | INBOX
isbg_testing-isbg_testing-1  | KeinSpam
isbg_testing-isbg_testing-1  | Papierkorb
isbg_testing-isbg_testing-1  | Spam
isbg_testing-isbg_testing-1  | #######FOLDERS#######
isbg_testing-isbg_testing-1  | running sa-learn
isbg_testing-isbg_testing-1  | starting spamassassin
isbg_testing-isbg_testing-1  | Starting SpamAssassin Mail Filter Daemon: spamd.
isbg_testing-isbg_testing-1  | updating SpamAssassin rules
isbg_testing-isbg_testing-1  | Update available for channel updates.spamassassin.org: -1 -> 1922358
isbg_testing-isbg_testing-1  | http: (curl) GET http://sa-update.spamassassin.org/MIRRORED.BY, success
isbg_testing-isbg_testing-1  | http: (curl) GET http://sa-update.ena.com/1922358.tar.gz, success
isbg_testing-isbg_testing-1  | http: (curl) GET http://sa-update.ena.com/1922358.tar.gz.asc, success
isbg_testing-isbg_testing-1  | Update was available, and was downloaded and installed successfully
isbg_testing-isbg_testing-1  | SpamTrainer Found 1 Config Files!
isbg_testing-isbg_testing-1  | Handling config file 1
isbg_testing-isbg_testing-1  | Training Spam for /var/lib/mailaccounts/isbg_test_heimpixel_de.conf
isbg_testing-isbg_testing-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost imap.ionos.de --imapuser isbg_test@heimpixel.de --spamc --teachonly --maxsize 120000 --partialrun 50 --learnspambox Spam --passwdfilename /var/lib/mailaccounts/isbg_test_heimpixel_de.conf --verbose " $USERNAME
isbg_testing-isbg_testing-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg_testing-isbg_testing-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track74716177ffe7511b0d642c4183af8d44
isbg_testing-isbg_testing-1  | Password file is /var/lib/mailaccounts/isbg_test_heimpixel_de.conf
isbg_testing-isbg_testing-1  | SpamFlags are []
isbg_testing-isbg_testing-1  | You need to specify your imap password and save it with the --savepw switch
isbg_testing-isbg_testing-1  | Use --help to see valid options and arguments
isbg_testing-isbg_testing-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost imap.ionos.de --imapuser isbg_test@heimpixel.de --spamc --teachonly --maxsize 120000 --partialrun 50 --learnhambox KeinSpam --passwdfilename /var/lib/mailaccounts/isbg_test_heimpixel_de.conf --verbose " $USERNAME
isbg_testing-isbg_testing-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg_testing-isbg_testing-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track74716177ffe7511b0d642c4183af8d44
isbg_testing-isbg_testing-1  | Password file is /var/lib/mailaccounts/isbg_test_heimpixel_de.conf
isbg_testing-isbg_testing-1  | SpamFlags are []
isbg_testing-isbg_testing-1  | You need to specify your imap password and save it with the --savepw switch
isbg_testing-isbg_testing-1  | Use --help to see valid options and arguments
isbg_testing-isbg_testing-1  | 0 hams moved
isbg_testing-isbg_testing-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost imap.ionos.de --imapuser isbg_test@heimpixel.de --spamc --teachonly --maxsize 120000 --partialrun 50 --learnhambox Sent --passwdfilename /var/lib/mailaccounts/isbg_test_heimpixel_de.conf --verbose " $USERNAME
isbg_testing-isbg_testing-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg_testing-isbg_testing-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track74716177ffe7511b0d642c4183af8d44
isbg_testing-isbg_testing-1  | Password file is /var/lib/mailaccounts/isbg_test_heimpixel_de.conf
isbg_testing-isbg_testing-1  | SpamFlags are []
isbg_testing-isbg_testing-1  | You need to specify your imap password and save it with the --savepw switch
isbg_testing-isbg_testing-1  | Use --help to see valid options and arguments
isbg_testing-isbg_testing-1  | 0 spams deleted
isbg_testing-isbg_testing-1  | starting Main Loop
isbg_testing-isbg_testing-1  | Spam Filter found 1 Config Files!
isbg_testing-isbg_testing-1  | Handling config file 1
isbg_testing-isbg_testing-1  | 0 spams moved to learn
isbg_testing-isbg_testing-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost imap.ionos.de --spamc --imapuser isbg_test@heimpixel.de  --partialrun 50 --maxsize 120000  --delete --expunge --spaminbox Spam --passwdfilename /var/lib/mailaccounts/isbg_test_heimpixel_de.conf --verbose " $USERNAME
isbg_testing-isbg_testing-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg_testing-isbg_testing-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track74716177ffe7511b0d642c4183af8d44
isbg_testing-isbg_testing-1  | Password file is /var/lib/mailaccounts/isbg_test_heimpixel_de.conf
isbg_testing-isbg_testing-1  | SpamFlags are ['\\Deleted']
isbg_testing-isbg_testing-1  | You need to specify your imap password and save it with the --savepw switch
isbg_testing-isbg_testing-1  | Use --help to see valid options and arguments```

**Comment by praul** [comment]
Since this is a test account, I could probably share the config file. Maybe you could try it out?

**my docker-compose.yml**
```
name: isbg_testing
services:
    isbg_testing:
        volumes:
            - ./data/cfg:/var/lib/mailaccounts
            - ./data/data:/var/lib/spamassassin/
        environment:
            - LIST_FOLDERS=true
            #- EXTRA_OPTIONS=--nouser-config
            - DETAILED_LOGGING=true
        restart: unless-stopped
        logging:
            options:
                max-size: 1g
        image: user4711/isbg:dev
```


**my test.conf in .data/cfg**

```
{
    "server": "imap.ionos.de",
    "username": "isbg_test@heimpixel.de",
    "password": "Vt4xj34FgUFAUQ",
    "spamHandling": "yes",
    "isGmail": "no",
    "spamSubject": "[SPAM?]",
    "report": "yes",
    "spamLifetime": 30,
    "folders": {
        "spam": "Spam",
        "ham": "KeinSpam",
        "sent": "Sent",
        "inbox": "INBOX"
    }
}
```

But since it say's "successfully read password file" I'm not sure if it's working or not
```
isbg_testing-isbg_testing-1  | Spam Filter found 1 Config Files!
isbg_testing-isbg_testing-1  | Handling config file 1
isbg_testing-isbg_testing-1  | 0 spams moved to learn
isbg_testing-isbg_testing-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost imap.ionos.de --spamc --imapuser isbg_test@heimpixel.de  --partialrun 50 --maxsize 120000  --delete --expunge --spaminbox Spam --passwdfilename /var/lib/mailaccounts/test.conf --verbose " $USERNAME
isbg_testing-isbg_testing-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
isbg_testing-isbg_testing-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track74716177ffe7511b0d642c4183af8d44
isbg_testing-isbg_testing-1  | Password file is /var/lib/mailaccounts/test.conf
isbg_testing-isbg_testing-1  | SpamFlags are ['\\Deleted']
isbg_testing-isbg_testing-1  | **Successfully read password file**
isbg_testing-isbg_testing-1  | **You need to specify your imap password and save it with the --savepw switch**
isbg_testing-isbg_testing-1  | Use --help to see valid options and arguments
```

**Complete docker-compose folder**
[isbg_testing.zip](https://github.com/user-attachments/files/18058635/isbg_testing.zip)

**Comment by DumpName** [comment]
Dude, please never ever post such sensitive information public. Even if it is just a test account! You could have pm'd me the details, but even then: what gurantees you that I will do nothing bad with it? Even if you could remove the mailaccount again, as this seems to be from your business: If a spam mailer is setup from this mailaddress and you notice only a couple of hours later your domain could already be blocked from some mailproviders as it would be sending spam.
I edited your post and removed the sensitive information ;).

I will have a look into it when I find the time during this week.

**Comment by romainhild** [comment]
I'm looking into this image and just saw this issue. 
From what I saw, imapFilters run as root in the container and isbg uses the user defined by USERNAME (debian-spamd). So root may have the right to read the mailaccounts files but not debian-spamd. I don't know if it helps, but maybe you can check that.

**Comment by praul** [comment]
Hi thanks, I checked it, chowned cfg dir and files to 101:102, for test purposes even chmodded the config files to 700. Still the same.
I don't know if these errors/warnings at startup have something to do with it:

```
isbg-isbg-1  | su: invalid option -- 'r'
isbg-isbg-1  | Try 'su --help' for more information.
isbg-isbg-1  | Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 442.
isbg-isbg-1  | Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 443.
```

**Comment by romainhild** [comment]
The uid of the spamd user is 783, see [here](https://github.com/DumpName/docker_isbg/blob/39cbb29dc7efce65458a17a42daae181e5b3d86a/Dockerfile#L33)

**Comment by praul** [comment]
I guess I figured out what the problem is. The lua script is passing the json conf file to isgb as passwdfilename
`" --passwdfilename " .. confFile`
This cannot work I guess, since isbg has its own way of storing passwords in files (obfuscated), see https://isbg.gitlab.io/isbg/manpage.isbg.html

**Comment by romainhild** [comment]
No, isbg obfuscate only the name of the file in which the password is stored. But it is only a json file with a "password" key in it.

**Comment by praul** [comment]
> No, isbg obfuscate only the name of the file in which the password is stored. But it is only a json file with a "password" key in it, like the configuration file in mailaccounts.

Hmm, okay, that is strange. I'm using this now with a modified command (see above)

> The uid of the spamd user is 783, see [here](https://github.com/DumpName/docker_isbg/blob/39cbb29dc7efce65458a17a42daae181e5b3d86a/Dockerfile#L33)

I could try this out as well, but since I chmodded the file to 700 for test purposes, this shouldn't matter, or am I wrong?

**Comment by Phoenix616** [comment]
Running into the same issue (with current latest so I assume 1.1.2), no matter what account or password I try it just spams that the password needs to be specified (folders are also logged properly if I enable that)

```
docker_isbg-1  | mkdir: cannot create directory '/root/currentState': File exists
docker_isbg-1  | delete isbg old lockfile if present
docker_isbg-1  | running sa-learn
docker_isbg-1  | config: registryboundaries: no tlds defined, need to run sa-update
docker_isbg-1  | starting spamassassin
docker_isbg-1  | child process [16] exited or timed out without signaling production of a PID file: exit 255 at /usr/sbin/spamd line 3141.
docker_isbg-1  | Starting SpamAssassin Mail Filter Daemon: updating SpamAssassin rules
docker_isbg-1  | Update available for channel updates.spamassassin.org: -1 -> 1926029
docker_isbg-1  | http: (curl) GET https://spamassassin.apache.org/updates/MIRRORED.BY, success
docker_isbg-1  | http: (curl) GET https://www.sa-update.pccc.com/1926029.tar.gz, success
docker_isbg-1  | http: (curl) GET https://www.sa-update.pccc.com/1926029.tar.gz.asc, success
docker_isbg-1  | Update was available, and was downloaded and installed successfully
docker_isbg-1  | SpamTrainer Found 3 Config Files!
docker_isbg-1  | Handling config file 1
docker_isbg-1  | Training Spam for /var/lib/mailaccounts/privat-new.conf
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | Handling config file 2
docker_isbg-1  | Training Spam for /var/lib/mailaccounts/privat.conf
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | Handling config file 3
docker_isbg-1  | Training Spam for /var/lib/mailaccounts/themoep.conf
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | starting Main Loop
docker_isbg-1  | Spam Filter found 3 Config Files!
docker_isbg-1  | Handling config file 1
docker_isbg-1  | 0 spams moved to learn
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | Handling config file 2
docker_isbg-1  | 0 spams moved to learn
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | Handling config file 3
docker_isbg-1  | 0 spams moved to learn
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
```

<details><summary>Verbose Log</summary>

```
docker_isbg-1  | su: invalid option -- 'r'
docker_isbg-1  | Try 'su --help' for more information.
docker_isbg-1  | Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 442.
docker_isbg-1  | Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/Razor2/Client/Config.pm line 443.
docker_isbg-1  | delete isbg old lockfile if present
docker_isbg-1  | running sa-learn
docker_isbg-1  | starting spamassassin
docker_isbg-1  | Starting SpamAssassin Mail Filter Daemon: spamd.
docker_isbg-1  | updating SpamAssassin rules
docker_isbg-1  | Update finished, no fresh updates were available
docker_isbg-1  | SpamTrainer Found 3 Config Files!
docker_isbg-1  | Handling config file 1
docker_isbg-1  | Training Spam for /var/lib/mailaccounts/privat-new.conf
docker_isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted1.example.com --imapuser redacted1@example.com --spamc --teachonly --maxsize 120000 --partialrun 200 --learnspambox Spam --passwdfilename /var/lib/mailaccounts/privat-new.conf --verbose " $USERNAME
docker_isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
docker_isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/trackdc3844d2822e0a06b8788d398b2840c9
docker_isbg-1  | Password file is /var/lib/mailaccounts/privat-new.conf
docker_isbg-1  | SpamFlags are []
docker_isbg-1  | Successfully read password file
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | Handling config file 2
docker_isbg-1  | Training Spam for /var/lib/mailaccounts/privat.conf
docker_isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted2.example.com --imapuser redacted2@example.com --spamc --teachonly --maxsize 120000 --partialrun 200 --learnspambox Spam --passwdfilename /var/lib/mailaccounts/privat.conf --verbose " $USERNAME
docker_isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
docker_isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track4e427f18f75239be8e0f498a8906a8d4
docker_isbg-1  | Password file is /var/lib/mailaccounts/privat.conf
docker_isbg-1  | SpamFlags are []
docker_isbg-1  | Successfully read password file
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | Handling config file 3
docker_isbg-1  | Training Spam for /var/lib/mailaccounts/themoep.conf
docker_isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted3.example.com --imapuser redacted3@example.com --spamc --teachonly --maxsize 120000 --partialrun 200 --learnspambox Spam --passwdfilename /var/lib/mailaccounts/themoep.conf --verbose " $USERNAME
docker_isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
docker_isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track80891e1357977f8a6232608a66a79d1e
docker_isbg-1  | Password file is /var/lib/mailaccounts/themoep.conf
docker_isbg-1  | SpamFlags are []
docker_isbg-1  | Successfully read password file
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | starting Main Loop
docker_isbg-1  | Spam Filter found 3 Config Files!
docker_isbg-1  | Handling config file 1
docker_isbg-1  | 0 spams moved to learn
docker_isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted1.example.com --spamc --imapuser redacted1@example.com  --partialrun 50 --maxsize 120000 --noreport --delete --expunge --spaminbox Spam --passwdfilename /var/lib/mailaccounts/privat-new.conf --verbose " $USERNAME
docker_isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
docker_isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/trackdc3844d2822e0a06b8788d398b2840c9
docker_isbg-1  | Password file is /var/lib/mailaccounts/privat-new.conf
docker_isbg-1  | SpamFlags are ['\\Deleted']
docker_isbg-1  | Successfully read password file
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | Handling config file 2
docker_isbg-1  | 0 spams moved to learn
docker_isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted2.example.com --spamc --imapuser redacted2@example.com  --partialrun 50 --maxsize 120000 --noreport --delete --expunge --spaminbox Spam --passwdfilename /var/lib/mailaccounts/privat.conf --verbose " $USERNAME
docker_isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
docker_isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track4e427f18f75239be8e0f498a8906a8d4
docker_isbg-1  | Password file is /var/lib/mailaccounts/privat.conf
docker_isbg-1  | SpamFlags are ['\\Deleted']
docker_isbg-1  | Successfully read password file
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
docker_isbg-1  | Handling config file 3
docker_isbg-1  | 0 spams moved to learn
docker_isbg-1  | su -c "/usr/local/pythonVenv/bin/isbg --imaphost redacted3.example.com --spamc --imapuser redacted3@example.com  --partialrun 50 --maxsize 120000 --noreport --delete --expunge --spaminbox Spam --passwdfilename /var/lib/mailaccounts/themoep.conf --verbose " $USERNAME
docker_isbg-1  | Lock file is /var/lib/spamassassin/.cache/isbg/lock
docker_isbg-1  | Trackfile starts with /var/lib/spamassassin/.cache/isbg/track80891e1357977f8a6232608a66a79d1e
docker_isbg-1  | Password file is /var/lib/mailaccounts/themoep.conf
docker_isbg-1  | SpamFlags are ['\\Deleted']
docker_isbg-1  | Successfully read password file
docker_isbg-1  | You need to specify your imap password and save it with the --savepw switch
docker_isbg-1  | Use --help to see valid options and arguments
```

</details> 

EDIT: Actually I seem to have figured out what the issue was: I had my account files only readable by the root user. That does not work for the isbg process as it's run with the docker-image-internal user `debian-spamd`. Setting the owner to `783` (the [`SPAMD_UID`](https://github.com/DumpName/docker_isbg/blob/391e533f8558504b24b5adbb20a871eb452c876c/Dockerfile#L34C5-L34C14)) solved it without making the files readable for everyone.
