### ISSUE TITLE
Folder Naming Issue

### ISSUE THREAD

**Issue by PaulCyberEngel** [DumpName/docker_isbg#6]
I've been testing docker_isbg, but I've run into a problem.

In my account config file, there are four folders that I need to define. When I set the "spam" folder to "Junk", I get the following error:

> ('select', 'Junk') returned ('NO', ['Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).']) - aborting

But when I set the folder name to "INBOX.Junk" I get this error:

> ('select', 'INBOX.INBOX.Junk') returned ('NO', ['Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).']) - aborting

It seems like the code is adding the prefix INBOX only when I've already done so. If I do not prefix, the code doesn't either.

**Comment by DumpName** [comment]
Hi,
I just added the option to list your folders/mailboxes during startup in the :dev image. You might want to have a look into that and fetch a listing of the folders.
I am not prefixing any additional names to the folder names.

From my experiance:
I am able to define just the folder name so if my spam folder is called "spam" setting the config file to this does work for me.

**Comment by PaulCyberEngel** [comment]
I’ve tried the :dev image and found the listFolders.lua in the imapfilter, but I get the following:

./listFolders.lua: line 1: confLoader: command not found
./listFolders.lua: line 2: settings: command not found
./listFolders.lua: line 5: syntax error near unexpected token `('
./listFolders.lua: line 5: `conftab = confLoader.scandir( settings.configFolder )'

Paul Engel
Author, Talk Show Host, Blogger, Podcaster, Preacher
and Overall Computer Geek
***@***.***

**Comment by DumpName** [comment]
Seems weired to me. Tested it on my pi and it works like a charm...
Could you please let me know what hardware you are using for you docker host?
Are you able to provide me with the following infos:
Output from `docker info` command
Output from `docker image inspect user4711/isbg:dev`

**Comment by PaulCyberEngel** [comment]
I’m running this on a Raspberry Pi 3 Model B Rev 1.2

docker info:
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 93
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 0v98qngvs2xxjw6xclnzm1ys5
  Is Manager: false
  Node Address: XX.XX.XX.XX
  Manager Addresses:
   XX.XX.XX.XX:2377
   XX.XX.XX.XX:2377
   XX.XX.XX.XX:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.103-v7+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 923.2MiB
 Name: worker4
 ID: BP7U:BEDU:UHSF:KPVD:IAJ5:JHMV:VL44:BOQN:KI2V:7URN:QTQC:CVER
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

docker image inspect user4711/isbg:dev
[
    {
        "Id": "sha256:7b884666069baef14a81c2c2017410fb0ae69800d257e50d319b0580b0953913",
        "RepoTags": [
            "user4711/isbg:dev"
        ],
        "RepoDigests": [
            ***@***.***:d27c2a30d839b56a5841de7385035df1590605d13ceceeae428026c511e6ce7b"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2022-12-03T18:30:05.36488792Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "TZ=UTC",
                "CRON_HOUR=1",
                "CRON_MINUTE=30",
                "HAM_BATCH_SIZE=50",
                "SPAM_BATCH_SIZE=50",
                "FILTER_BATCH_SIZE=50",
                "MAX_MAIL_SIZE=120000",
                "USERNAME=debian-spamd",
                "EXTRA_OPTIONS=--nouser-config",
                "PYZOR_SITE=public.pyzor.org:24441",
                "DETAILED_LOGGING=false",
                "LIST_FOLDERS=false"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "/root/status.sh"
                ],
                "Interval": 60000000000,
                "Timeout": 10000000000,
                "StartPeriod": 300000000000
            },
            "Image": "",
            "Volumes": {
                "/var/lib/mailaccounts": {},
                "/var/lib/spamassassin": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/root/startup.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "",
                "org.label-schema.license": "GNU GPL-3.0",
                "org.label-schema.name": "spamassassin",
                "org.label-schema.vcs-ref": ""
            }
        },
        "Architecture": "arm",
        "Variant": "v7",
        "Os": "linux",
        "Size": 270627509,
        "VirtualSize": 270627509,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/afbc24b5d16b95a6d1c2deb35f22feeebd3e3c58caab16bd3c430a5988c21db9/diff:/var/lib/docker/overlay2/ddfec89e04a4c198e65d84ae08dd1b4365587a2b0a893d4d87ef51d748617f4e/diff:/var/lib/docker/overlay2/a1add7b79755c9369f60b37265f2d28b205a6aa9d4d616299cf85f2348c63955/diff:/var/lib/docker/overlay2/00a01b47691ba0bff8432c0a77b7b2d129cdcfaf489c29044b55c0c25d917ebf/diff:/var/lib/docker/overlay2/b18ad073e9828edde0554a4a2e967bbf02ef15f296705a80beab0ca30fe98e69/diff:/var/lib/docker/overlay2/7ac5cbb113f5181053404d4a0e3d0c2837af31198f58823d40e35dbc11f23f31/diff:/var/lib/docker/overlay2/fb3e47283735027b594ca2b95aaef39ee6af875b639f1ed86a59db853d2e7e8f/diff:/var/lib/docker/overlay2/27926bbf8d2ad978c21f6185d12009c970a511a542f2d58218b2423bd0fa4f63/diff:/var/lib/docker/overlay2/99874b6d4e28b518d78041ad2c687fc1c7c923b27437549f49ff5449a8fdd700/diff:/var/lib/docker/overlay2/e14ab516a81d9175165002d1b0e595c8973639406691006f537d111925c4b0d6/diff:/var/lib/docker/overlay2/d6e9c9ada10111fe08ace2c8d70ee2fe33a7f1da8ef8cc5f9cb6fb319deb0e18/diff",
                "MergedDir": "/var/lib/docker/overlay2/f6069e85b1dadda59ae0b717efe42088aa1e24e1cc3e064d77bfc409932ba963/merged",
                "UpperDir": "/var/lib/docker/overlay2/f6069e85b1dadda59ae0b717efe42088aa1e24e1cc3e064d77bfc409932ba963/diff",
                "WorkDir": "/var/lib/docker/overlay2/f6069e85b1dadda59ae0b717efe42088aa1e24e1cc3e064d77bfc409932ba963/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:8dd4eba25282d2726fbd32ada69c4d27dd2c289d5fb468b3417dfd80b2ccb9c8",
                "sha256:742ea1c8eac42e231e5275bd45f99c7ed13516f57d0f402ca4167e60129f56b1",
                "sha256:dcb939a4a096adc6b7fba460c863fec3ced63063e8ebc8cc25b0cd686593d271",
                "sha256:35f2275d813f12f80b202398c8a2366a14897795dc8b72346dceab1af8935873",
                "sha256:aafc5b37b60612c069a2cc152c911b157ef8a0b1457b42bb6fbb1aaac88c6e9c",
                "sha256:57000ff9896fe0a0ef65fe56790545d6bfe7196606249370dcc102f2561b1815",
                "sha256:3b4320b5e28755270fe2092b30d7b2387e90567df532a3317998d36f4cfe4ec0",
                "sha256:0070f32ce542ba283ae1f59decc82067d467c861acd4afdad4e5ab5aabf043c8",
                "sha256:e5ad3247aa72c9efc0fc65cfe02d45ed2654c7573fa0c5f21d1e8dc4a63e74b3",
                "sha256:2327d0517011aa63037f0ba1dcff0baeab622d63984577148cdcde7f82e18579",
                "sha256:b1d96c17f70fc38d02dc7fbd71011d3a832379707a8f58858673791593a66603",
                "sha256:77251c15ed4c287cc020adafb21a52f90d5dc503142585d960f182e86dcbc689"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]


Paul Engel
Author, Talk Show Host, Blogger, Podcaster, Preacher
and Overall Computer Geek
***@***.***

**Comment by cfe84** [comment]
Hey, got the same issue:

```
######MAILBOXES######
Ham
Newsletter
Junk
Sent
#######FOLDERS#######
old
INBOX
```

```
('select', 'Junk') returned ('NO', ['Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.001 + 0.000 secs).'])
```

I'm wondering if that's because it's trying to select a folder rather than a mailbox. I'll try to dig a bit deeper to figure out what's happening

**Comment by DumpName** [comment]
Sorry for the missing response from my site.
I was not able to reproduce it yet. (Maybe my own mailprovider is the weired one here)

**Comment by DumpName** [comment]
I am investigating a little bit in what happens here. To give you some options on what to try next:
This problem occures inside of imapfilter, or to be specific inside the spamFilter.lua that is executed by imapfilter.
When I am not mistaken it sould be possible to access mailboxes in folders by separating them via "/"
To quote from the imapfilter docs:

> -- Move messages to the "announce" mailbox inside the "lists" folder.
results:move_messages(account1['lists/announce'])

Could you try to set the foldername to "INBOX/Junk"?
Unfortunately I am still not able to reproduce the issue on my side at the moment.
